# Generated by Django 5.0.7 on 2024-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_SAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sara',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sarda',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sari',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sarv',
            name='tipo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
