# Generated by Django 5.0.7 on 2024-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_SAR', '0002_sara_tipo_sarda_tipo_sari_tipo_sarv_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('destino', models.CharField(default='', max_length=50)),
                ('code_destino', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(max_length=10)),
                ('tipo', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='sara',
        ),
        migrations.DeleteModel(
            name='sarda',
        ),
        migrations.DeleteModel(
            name='sari',
        ),
        migrations.DeleteModel(
            name='sarv',
        ),
    ]
