# Generated by Django 5.0.7 on 2024-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_SAR', '0003_sar_delete_sara_delete_sarda_delete_sari_delete_sarv'),
    ]

    operations = [
        migrations.AddField(
            model_name='sar',
            name='old_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
